# apiVersion: v1
# kind: Service
# metadata:
#   name: wordpress
#   labels:
#     app: wordpress
# spec:
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 80
#   selector:
#     app: wordpress
#     tier: frontend
#   type: LoadBalancer

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-wp-pv-claim
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.wordpress_app.storage }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-wordpress
  labels:
    app: wordpress
spec:
  replicas: {{ .Values.wordpress_app.number_of_replicas }}
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - image: {{ .Values.wordpress_app.image }}
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: {{ .Release.Name }}-wordpress-mysql
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-mysql-pass
              key: password
        - name: WORDPRESS_DB_USER
          value: {{ .Values.wordpress_app.db_user }}
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-wp-pv-claim
