apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-wordpress
  labels:
    app: wordpress
spec:
  selector:
    app: wordpress
    tier: frontend
  ports:
    - protocol: TCP
      port: {{ .Values.wordpress_app.port }}
      {{- if not .Values.ingress.enabled }}
      nodePort: {{ .Values.wordpress_app.nodePort }}
      {{- end }}
{{- if .Values.ingress.enabled }}
      targetPort: {{ .Values.wordpress_app.port }}
  type: ClusterIP
{{- else }}
  type: NodePort
{{- end}}
